<?php

namespace App\Support;

class DatasetOptions
{
    public static function regions(): array
    {
        return [
            "auburn" => "auburn",
            "birmingham" => "birmingham",
            "dothan" => "dothan",
            "florence / muscle shoals" => "florence / muscle shoals",
            "gadsden-anniston" => "gadsden-anniston",
            "huntsville / decatur" => "huntsville / decatur",
            "mobile" => "mobile",
            "montgomery" => "montgomery",
            "tuscaloosa" => "tuscaloosa",
            "anchorage / mat-su" => "anchorage / mat-su",
            "fairbanks" => "fairbanks",
            "kenai peninsula" => "kenai peninsula",
            "other" => "other",
            "flagstaff / sedona" => "flagstaff / sedona",
            "mohave county" => "mohave county",
            "phoenix" => "phoenix",
            "prescott" => "prescott",
            "sierra vista" => "sierra vista",
            "tucson" => "tucson",
            "yuma" => "yuma",
            "fayetteville" => "fayetteville",
            "fort smith" => "fort smith",
            "jonesboro" => "jonesboro",
            "little rock" => "little rock",
            "texarkana" => "texarkana",
            "bakersfield" => "bakersfield",
            "chico" => "chico",
            "fresno / madera" => "fresno / madera",
            "gold country" => "gold country",
            "hanford-corcoran" => "hanford-corcoran",
            "humboldt county" => "humboldt county",
            "inland empire" => "inland empire",
            "los angeles" => "los angeles",
            "mendocino county" => "mendocino county",
            "merced" => "merced",
            "modesto" => "modesto",
            "monterey bay" => "monterey bay",
            "orange county" => "orange county",
            "palm springs" => "palm springs",
            "redding" => "redding",
            "reno / tahoe" => "reno / tahoe",
            "sacramento" => "sacramento",
            "san diego" => "san diego",
            "san luis obispo" => "san luis obispo",
            "santa barbara" => "santa barbara",
            "santa maria" => "santa maria",
            "SF bay area" => "SF bay area",
            "stockton" => "stockton",
            "susanville" => "susanville",
            "ventura county" => "ventura county",
            "visalia-tulare" => "visalia-tulare",
            "yuba-sutter" => "yuba-sutter",
            "boulder" => "boulder",
            "colorado springs" => "colorado springs",
            "denver" => "denver",
            "fort collins / north CO" => "fort collins / north CO",
            "high rockies" => "high rockies",
            "pueblo" => "pueblo",
            "western slope" => "western slope",
            "eastern CT" => "eastern CT",
            "hartford" => "hartford",
            "new haven" => "new haven",
            "northwest CT" => "northwest CT",
            "washington DC" => "washington DC",
            "delaware" => "delaware",
            "daytona beach" => "daytona beach",
            "florida keys" => "florida keys",
            "ft myers / SW florida" => "ft myers / SW florida",
            "gainesville" => "gainesville",
            "heartland florida" => "heartland florida",
            "jacksonville" => "jacksonville",
            "lakeland" => "lakeland",
            "north central FL" => "north central FL",
            "ocala" => "ocala",
            "okaloosa / walton" => "okaloosa / walton",
            "orlando" => "orlando",
            "panama city" => "panama city",
            "pensacola" => "pensacola",
            "sarasota-bradenton" => "sarasota-bradenton",
            "south florida" => "south florida",
            "space coast" => "space coast",
            "st augustine" => "st augustine",
            "tallahassee" => "tallahassee",
            "tampa bay area" => "tampa bay area",
            "treasure coast" => "treasure coast",
            "albany" => "albany",
            "athens" => "athens",
            "atlanta" => "atlanta",
            "augusta" => "augusta",
            "brunswick" => "brunswick",
            "columbus" => "columbus",
            "macon / warner robins" => "macon / warner robins",
            "northwest GA" => "northwest GA",
            "savannah / hinesville" => "savannah / hinesville",
            "statesboro" => "statesboro",
            "valdosta" => "valdosta",
            "hawaii" => "hawaii",
            "boise" => "boise",
            "east idaho" => "east idaho",
            "lewiston / clarkston" => "lewiston / clarkston",
            "pullman / moscow" => "pullman / moscow",
            "spokane / coeur d'alene" => "spokane / coeur d'alene",
            "twin falls" => "twin falls",
            "bloomington-normal" => "bloomington-normal",
            "champaign urbana" => "champaign urbana",
            "chicago" => "chicago",
            "decatur" => "decatur",
            "la salle co" => "la salle co",
            "mattoon-charleston" => "mattoon-charleston",
            "peoria" => "peoria",
            "quad cities IA/IL" => "quad cities IA/IL",
            "rockford" => "rockford",
            "southern illinois" => "southern illinois",
            "springfield" => "springfield",
            "st louis MO" => "st louis MO",
            "bloomington" => "bloomington",
            "evansville" => "evansville",
            "fort wayne" => "fort wayne",
            "indianapolis" => "indianapolis",
            "kokomo" => "kokomo",
            "lafayette / west lafayette" => "lafayette / west lafayette",
            "muncie / anderson" => "muncie / anderson",
            "richmond" => "richmond",
            "south bend / michiana" => "south bend / michiana",
            "terre haute" => "terre haute",
            "ames" => "ames",
            "cedar rapids" => "cedar rapids",
            "des moines" => "des moines",
            "dubuque" => "dubuque",
            "iowa city" => "iowa city",
            "mason city" => "mason city",
            "omaha / council bluffs" => "omaha / council bluffs",
            "sioux city" => "sioux city",
            "waterloo / cedar falls" => "waterloo / cedar falls",
            "kansas city MO" => "kansas city MO",
            "lawrence" => "lawrence",
            "manhattan" => "manhattan",
            "northwest KS" => "northwest KS",
            "salina" => "salina",
            "topeka" => "topeka",
            "wichita" => "wichita",
            "bowling green" => "bowling green",
            "eastern kentucky" => "eastern kentucky",
            "lexington" => "lexington",
            "louisville" => "louisville",
            "owensboro" => "owensboro",
            "western KY" => "western KY",
            "baton rouge" => "baton rouge",
            "central louisiana" => "central louisiana",
            "lafayette" => "lafayette",
            "lake charles" => "lake charles",
            "monroe" => "monroe",
            "new orleans" => "new orleans",
            "shreveport" => "shreveport",
            "maine" => "maine",
            "annapolis" => "annapolis",
            "baltimore" => "baltimore",
            "cumberland valley" => "cumberland valley",
            "eastern shore" => "eastern shore",
            "frederick" => "frederick",
            "southern maryland" => "southern maryland",
            "western maryland" => "western maryland",
            "boston" => "boston",
            "cape cod / islands" => "cape cod / islands",
            "south coast" => "south coast",
            "western massachusetts" => "western massachusetts",
            "worcester / central MA" => "worcester / central MA",
            "ann arbor" => "ann arbor",
            "battle creek" => "battle creek",
            "central michigan" => "central michigan",
            "detroit metro" => "detroit metro",
            "flint" => "flint",
            "grand rapids" => "grand rapids",
            "holland" => "holland",
            "jackson" => "jackson",
            "kalamazoo" => "kalamazoo",
            "lansing" => "lansing",
            "muskegon" => "muskegon",
            "northern michigan" => "northern michigan",
            "port huron" => "port huron",
            "saginaw-midland-baycity" => "saginaw-midland-baycity",
            "southwest michigan" => "southwest michigan",
            "the thumb" => "the thumb",
            "upper peninsula" => "upper peninsula",
            "bemidji" => "bemidji",
            "brainerd" => "brainerd",
            "duluth / superior" => "duluth / superior",
            "fargo / moorhead" => "fargo / moorhead",
            "mankato" => "mankato",
            "minneapolis / st paul" => "minneapolis / st paul",
            "rochester" => "rochester",
            "st cloud" => "st cloud",
            "gulfport / biloxi" => "gulfport / biloxi",
            "north mississippi" => "north mississippi",
            "columbia / jeff city" => "columbia / jeff city",
            "joplin" => "joplin",
            "kirksville" => "kirksville",
            "lake of the ozarks" => "lake of the ozarks",
            "southeast missouri" => "southeast missouri",
            "st joseph" => "st joseph",
            "billings" => "billings",
            "bozeman" => "bozeman",
            "butte" => "butte",
            "great falls" => "great falls",
            "helena" => "helena",
            "kalispell" => "kalispell",
            "missoula" => "missoula",
            "asheville" => "asheville",
            "boone" => "boone",
            "charlotte" => "charlotte",
            "eastern NC" => "eastern NC",
            "greensboro" => "greensboro",
            "hickory / lenoir" => "hickory / lenoir",
            "raleigh / durham / CH" => "raleigh / durham / CH",
            "wilmington" => "wilmington",
            "winston-salem" => "winston-salem",
            "grand island" => "grand island",
            "lincoln" => "lincoln",
            "las vegas" => "las vegas",
            "central NJ" => "central NJ",
            "jersey shore" => "jersey shore",
            "north jersey" => "north jersey",
            "south jersey" => "south jersey",
            "albuquerque" => "albuquerque",
            "las cruces" => "las cruces",
            "santa fe / taos" => "santa fe / taos",
            "binghamton" => "binghamton",
            "buffalo" => "buffalo",
            "catskills" => "catskills",
            "chautauqua" => "chautauqua",
            "elmira-corning" => "elmira-corning",
            "finger lakes" => "finger lakes",
            "glens falls" => "glens falls",
            "hudson valley" => "hudson valley",
            "ithaca" => "ithaca",
            "long island" => "long island",
            "new york city" => "new york city",
            "plattsburgh-adirondacks" => "plattsburgh-adirondacks",
            "syracuse" => "syracuse",
            "twin tiers NY/PA" => "twin tiers NY/PA",
            "utica-rome-oneida" => "utica-rome-oneida",
            "watertown" => "watertown",
            "new hampshire" => "new hampshire",
            "grand forks" => "grand forks",
            "akron / canton" => "akron / canton",
            "ashtabula" => "ashtabula",
            "chillicothe" => "chillicothe",
            "cincinnati" => "cincinnati",
            "cleveland" => "cleveland",
            "dayton / springfield" => "dayton / springfield",
            "lima / findlay" => "lima / findlay",
            "mansfield" => "mansfield",
            "northern panhandle" => "northern panhandle",
            "parkersburg-marietta" => "parkersburg-marietta",
            "sandusky" => "sandusky",
            "toledo" => "toledo",
            "tuscarawas co" => "tuscarawas co",
            "youngstown" => "youngstown",
            "zanesville / cambridge" => "zanesville / cambridge",
            "lawton" => "lawton",
            "northwest OK" => "northwest OK",
            "oklahoma city" => "oklahoma city",
            "stillwater" => "stillwater",
            "texoma" => "texoma",
            "tulsa" => "tulsa",
            "bend" => "bend",
            "corvallis/albany" => "corvallis/albany",
            "east oregon" => "east oregon",
            "eugene" => "eugene",
            "klamath falls" => "klamath falls",
            "medford-ashland" => "medford-ashland",
            "oregon coast" => "oregon coast",
            "portland" => "portland",
            "roseburg" => "roseburg",
            "salem" => "salem",
            "altoona-johnstown" => "altoona-johnstown",
            "erie" => "erie",
            "harrisburg" => "harrisburg",
            "lancaster" => "lancaster",
            "lehigh valley" => "lehigh valley",
            "meadville" => "meadville",
            "philadelphia" => "philadelphia",
            "pittsburgh" => "pittsburgh",
            "poconos" => "poconos",
            "reading" => "reading",
            "scranton / wilkes-barre" => "scranton / wilkes-barre",
            "state college" => "state college",
            "williamsport" => "williamsport",
            "york" => "york",
            "rhode island" => "rhode island",
            "charleston" => "charleston",
            "columbia" => "columbia",
            "florence" => "florence",
            "greenville / upstate" => "greenville / upstate",
            "hilton head" => "hilton head",
            "myrtle beach" => "myrtle beach",
            "rapid city / west SD" => "rapid city / west SD",
            "sioux falls / SE SD" => "sioux falls / SE SD",
            "chattanooga" => "chattanooga",
            "clarksville" => "clarksville",
            "cookeville" => "cookeville",
            "knoxville" => "knoxville",
            "memphis" => "memphis",
            "nashville" => "nashville",
            "tri-cities" => "tri-cities",
            "abilene" => "abilene",
            "amarillo" => "amarillo",
            "austin" => "austin",
            "beaumont / port arthur" => "beaumont / port arthur",
            "brownsville" => "brownsville",
            "college station" => "college station",
            "corpus christi" => "corpus christi",
            "dallas / fort worth" => "dallas / fort worth",
            "el paso" => "el paso",
            "galveston" => "galveston",
            "houston" => "houston",
            "killeen / temple / ft hood" => "killeen / temple / ft hood",
            "laredo" => "laredo",
            "lubbock" => "lubbock",
            "mcallen / edinburg" => "mcallen / edinburg",
            "odessa / midland" => "odessa / midland",
            "san angelo" => "san angelo",
            "san antonio" => "san antonio",
            "san marcos" => "san marcos",
            "tyler / east TX" => "tyler / east TX",
            "victoria" => "victoria",
            "waco" => "waco",
            "wichita falls" => "wichita falls",
            "logan" => "logan",
            "salt lake city" => "salt lake city",
            "st george" => "st george",
            "vermont" => "vermont",
            "charlottesville" => "charlottesville",
            "danville" => "danville",
            "fredericksburg" => "fredericksburg",
            "harrisonburg" => "harrisonburg",
            "lynchburg" => "lynchburg",
            "new river valley" => "new river valley",
            "norfolk / hampton roads" => "norfolk / hampton roads",
            "roanoke" => "roanoke",
            "southwest VA" => "southwest VA",
            "winchester" => "winchester",
            "bellingham" => "bellingham",
            "kennewick-pasco-richland" => "kennewick-pasco-richland",
            "moses lake" => "moses lake",
            "olympic peninsula" => "olympic peninsula",
            "seattle-tacoma" => "seattle-tacoma",
            "skagit / island / SJI" => "skagit / island / SJI",
            "wenatchee" => "wenatchee",
            "yakima" => "yakima",
            "eastern panhandle" => "eastern panhandle",
            "morgantown" => "morgantown",
            "appleton-oshkosh-FDL" => "appleton-oshkosh-FDL",
            "eau claire" => "eau claire",
            "green bay" => "green bay",
            "janesville" => "janesville",
            "kenosha-racine" => "kenosha-racine",
            "la crosse" => "la crosse",
            "madison" => "madison",
            "milwaukee" => "milwaukee",
            "northern WI" => "northern WI",
            "sheboygan" => "sheboygan",
            "wausau" => "wausau",
            "wyoming" => "wyoming",
        ];
    }


    public static function states(): array
    {
        return [
            "al" => "al",
            "ak" => "ak",
            "az" => "az",
            "ar" => "ar",
            "ca" => "ca",
            "co" => "co",
            "ct" => "ct",
            "dc" => "dc",
            "de" => "de",
            "fl" => "fl",
            "ga" => "ga",
            "hi" => "hi",
            "id" => "id",
            "il" => "il",
            "in" => "in",
            "ia" => "ia",
            "ks" => "ks",
            "ky" => "ky",
            "la" => "la",
            "me" => "me",
            "md" => "md",
            "ma" => "ma",
            "mi" => "mi",
            "mn" => "mn",
            "ms" => "ms",
            "mo" => "mo",
            "mt" => "mt",
            "nc" => "nc",
            "ne" => "ne",
            "nv" => "nv",
            "nj" => "nj",
            "nm" => "nm",
            "ny" => "ny",
            "nh" => "nh",
            "nd" => "nd",
            "oh" => "oh",
            "ok" => "ok",
            "or" => "or",
            "pa" => "pa",
            "ri" => "ri",
            "sc" => "sc",
            "sd" => "sd",
            "tn" => "tn",
            "tx" => "tx",
            "ut" => "ut",
            "vt" => "vt",
            "va" => "va",
            "wa" => "wa",
            "wv" => "wv",
            "wi" => "wi",
            "wy" => "wy",
        ];
    }


    public static function manufacturers(): array
    {
        return [
            "gmc" => "gmc",
            "chevrolet" => "chevrolet",
            "toyota" => "toyota",
            "ford" => "ford",
            "jeep" => "jeep",
            "nissan" => "nissan",
            "ram" => "ram",
            "cadillac" => "cadillac",
            "honda" => "honda",
            "dodge" => "dodge",
            "lexus" => "lexus",
            "jaguar" => "jaguar",
            "chrysler" => "chrysler",
            "volvo" => "volvo",
            "audi" => "audi",
            "infiniti" => "infiniti",
            "lincoln" => "lincoln",
            "other" => "other",
            "subaru" => "subaru",
            "acura" => "acura",
            "hyundai" => "hyundai",
            "mercedes-benz" => "mercedes-benz",
            "bmw" => "bmw",
            "mitsubishi" => "mitsubishi",
            "volkswagen" => "volkswagen",
            "mazda" => "mazda",
            "porsche" => "porsche",
            "kia" => "kia",
            "buick" => "buick",
            "rover" => "rover",
            "mini" => "mini",
            "pontiac" => "pontiac",
        ];
    }


    public static function paintColors(): array
    {
        return [
            "white" => "white",
            "blue" => "blue",
            "red" => "red",
            "black" => "black",
            "silver" => "silver",
            "grey" => "grey",
            "brown" => "brown",
            "orange" => "orange",
            "green" => "green",
            "yellow" => "yellow",
            "custom" => "custom",
            "purple" => "purple",
        ];
    }


    public static function fuels(): array
    {
        return [
            "gas" => "gas",
            "other" => "other",
            "diesel" => "diesel",
            "hybrid" => "hybrid",
            "electric" => "electric",
        ];
    }


    public static function cylinders(): array
    {
        return [
            "8" => "8",
            "6" => "6",
            "4" => "4",
            "5" => "5",
            "10" => "10",
            "other" => "other",
            "3" => "3",
            "12" => "12",
        ];
    }


    public static function transmissions(): array
    {
        return [
            "other" => "other",
            "automatic" => "automatic",
            "manual" => "manual",
        ];
    }


    public static function drives(): array
    {
        return [
            "rwd" => "rwd",
            "4wd" => "4wd",
            "fwd" => "fwd",
        ];
    }


    public static function types(): array
    {
        return [
            "pickup" => "pickup",
            "truck" => "truck",
            "other" => "other",
            "SUV" => "SUV",
            "hatchback" => "hatchback",
            "mini-van" => "mini-van",
            "sedan" => "sedan",
            "offroad" => "offroad",
            "coupe" => "coupe",
            "convertible" => "convertible",
            "wagon" => "wagon",
            "van" => "van",
            "bus" => "bus",
        ];
    }
}
